/**
 * assemble-readme.ts — template + generated assets → README.md.
 *
 * Builds three token blocks:
 *   {{HERO}}            dual-theme <picture> for the hero SVG
 *   {{AGENT_REGISTRY}}  the card grid (featured card spans two columns)
 *   {{TELEMETRY}}       dual-theme <picture> for the telemetry strip
 *
 * Each block is dark/light aware via <picture> + prefers-color-scheme (§2.1).
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { REPO_ROOT } from "./lib/config.js";
import type { CardManifestEntry } from "./build-cards.js";

const ASSETS = "assets";
const GEN = `${ASSETS}/generated`;

/** Dual-theme <picture>. GitHub swaps the source on prefers-color-scheme. */
function picture(darkPath: string, lightPath: string, alt: string, width?: number): string {
  const w = width ? ` width="${width}"` : "";
  return (
    `<picture>` +
    `<source media="(prefers-color-scheme: dark)" srcset="${darkPath}">` +
    `<source media="(prefers-color-scheme: light)" srcset="${lightPath}">` +
    `<img alt="${alt}" src="${lightPath}"${w}>` +
    `</picture>`
  );
}

function linkedPicture(entry: CardManifestEntry): string {
  const pic = picture(
    `${GEN}/${entry.id}-dark.svg`,
    `${GEN}/${entry.id}-light.svg`,
    `${entry.id} — ${entry.status}`,
  );
  return entry.url ? `<a href="${entry.url}">${pic}</a>` : pic;
}

function buildRegistry(): string {
  const manifestPath = resolve(REPO_ROOT, GEN, "cards.json");
  if (!existsSync(manifestPath)) {
    throw new Error("assets/generated/cards.json missing — run `npm run build:cards` first.");
  }
  const cards = (JSON.parse(readFileSync(manifestPath, "utf8")) as CardManifestEntry[])
    .slice()
    .sort((a, b) => a.order - b.order);

  const featured = cards.filter((c) => c.featured);
  const rest = cards.filter((c) => !c.featured);

  const rows: string[] = [];

  // Featured card, colspan=2, top row.
  for (const f of featured) {
    rows.push(`  <tr><td colspan="2" align="center">${linkedPicture(f)}</td></tr>`);
  }

  // Remaining cards, two per row.
  for (let i = 0; i < rest.length; i += 2) {
    const left = rest[i];
    const right = rest[i + 1];
    const cells = [left, right]
      .filter(Boolean)
      .map((c) => `<td align="center">${linkedPicture(c!)}</td>`)
      .join("");
    rows.push(`  <tr>${cells}</tr>`);
  }

  return `<table>\n${rows.join("\n")}\n</table>`;
}

function buildHero(): string {
  const dark = `${ASSETS}/hero-dark.svg`;
  const light = `${ASSETS}/hero-light.svg`;
  const present = existsSync(resolve(REPO_ROOT, dark)) && existsSync(resolve(REPO_ROOT, light));
  if (!present) {
    // Hero is a Day-3 hand-built asset; emit a placeholder marker until it lands.
    return "<!-- HERO: assets/hero-{dark,light}.svg not yet built (Day 3) -->";
  }
  return picture(dark, light, "Caleb Funderburk — Agent Orchestrator Console", 1000);
}

function buildTelemetry(): string {
  const dark = `${GEN}/telemetry-dark.svg`;
  const light = `${GEN}/telemetry-light.svg`;
  if (!existsSync(resolve(REPO_ROOT, dark))) {
    return "<!-- TELEMETRY: run `npm run build:telemetry` -->";
  }
  return picture(dark, light, "Telemetry readout", 788);
}

function main() {
  const tplPath = resolve(REPO_ROOT, "templates", "README.tpl.md");
  const tpl = readFileSync(tplPath, "utf8");

  const out = tpl
    .replace("{{HERO}}", buildHero())
    .replace("{{AGENT_REGISTRY}}", buildRegistry())
    .replace("{{TELEMETRY}}", buildTelemetry());

  const banner =
    "<!-- Generated by scripts/assemble-readme.ts from templates/README.tpl.md — do not hand-edit. -->\n\n";
  writeFileSync(resolve(REPO_ROOT, "README.md"), banner + out, "utf8");
  console.log("  ✓ README.md assembled");
}

main();
